#!/bin/sh

regex='@company\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]]
then 
    echo Your email $email satisfies the condition
    exit 0
else 
    echo Your email $email does not satisfy the condition
    exit 1
fi
